sudo: required
services:
  - docker

before_install:
  - docker build -t kat1330/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run kat1330/client-test npm test -- --coverage

after_success:
  - docker build -t kat1330/docker-solution-client ./client
  - docker build -t kat1330/docker-solution-nginx ./nginx
  - docker build -t kat1330/docker-solution-api ./server
  - docker build -t kat1330/docker-solution-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kat1330/docker-solution-client
  - docker push kat1330/docker-solution-nginx
  - docker push kat1330/docker-solution-api
  - docker push kat1330/docker-solution-worker

deploy: 
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-solution"
  env: "DockerSolution-env"
  bucket_name: "elasticbeanstalk-us-west-1-221954440452"
  bucker_path: "docker-solution"
  access_key_id: 
      secure: "$AWS_ACCESS_KEY"
  secret_access_key: 
      secure: "$AWS_SECRET_KEY"
  on: 
    branch: master