sudo: required
services:
  - docker

before_install:
  - docker build -t kat1330/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run kat1330/client-test npm test -- --coverage

after_success:
  - docker build -t kat1330/docker-solution-client ./client
  - docker build -t kat1330/docker-solution-nginx ./nginx
  - docker build -t kat1330/docker-solution-api ./api
  - docker build -t kat1330/docker-solution-worker ./worker

